### PR TITLE
Fixed problems in case someone ever loads more than 54 sectors

### PR DESCRIPTION
**Pull request by truemaker**
If you load more than 54 sectors to address 0x1000 it would overwrite the bootloader

### CODE REVIEW

**Comment by truemaker** [comment]
well this turned into a lot of changes to fix stuff that didn't work properly

**Comment by Mastcharub** [comment]
testing...

**Review by Mastcharub — APPROVED** [review]
Tested. It Works just Fine!

**Comment by truemaker** [comment]
can someone merge this please

**Pull request merged**
