### PR TITLE
Documentation Refactoring

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>
<br>

*Please check the **[Preview]**.*

<br>
<br>

### Repository Suggestions

  <br>

- **Choose A License**

  **⤷** *https://choosealicense.com/licenses/*

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`

<br>
<br>

### Changes

- General formatting / spacing
- Added license badge placeholder
- Split up documentation
- Added quicklinks

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/MellOs
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

### CODE REVIEW

**Comment by mell-o-tron** [comment]
Good idea, but I'm not particularly a big fan of the style you used. 

I'll definitely take some of the suggestions and ideas in a future refactoring of the documentation.

**Comment by ElectronicsArchiver** [comment]
Why don't you just tell me what you don't like about it?

**Comment by ElectronicsArchiver** [comment]
> so I'd like you to list a few of the suggestions you have in a comment here, if you don't mind :)

I'm not quite sure if I follow, suggestions regarding documentation?
If so, about styling principles or content?

> Also, this isn't really documentation, and most of the paragraphs you put into different markdown files were quite tiny, and probably did not really deserve their own file.

Well I didn't have access to the `Projects` tab, otherwise all
of the `Work In progress`, `Planned` as well as `Bugs` could be
put in there...

> I don't like the abundance of styling you used, it makes it confusing to read (at least to me, I'm all weird with styling), and I'd like you to keep the original text intact (e.g. the "resources" list looked better as a plain paragraph to me).

That's far from abundance but if it's only the resources paragraph, sure.

> A better idea would be writing somewhat of an actual documentation for the current functionalities, that the contributors could upload as they add or change features, which you could work on if you like.

Well you should know best what's included, I'm more aquainted with taking 
existing content and refactoring / formatting / rewording / .. it.

**Comment by ElectronicsArchiver** [comment]
> I was referring to suggestions regarding the contents of the current README; one example might be that I noticed you used the name of the kernel in the README, while I didn't, and that seems like a reasonable choice. Also, the suggestion about choosing a licence is pretty good.

Ah, right.

> If you have any proposals regarding the contents of the README or the structure of the project in general, you're still very welcome to present them :)

Well, how about using a `Source` folder so the project root isn't
cluttered and people don't have to scroll down to find the README.

Repos often have:
`/Resources/` *of the repo, not for the source ofc*
`/Source/`
`/Documentation/`

**Comment by ElectronicsArchiver** [comment]
> Regarding the source folder, I kind the current structure is fine for now, after all the [linux repo](https://github.com/torvalds/linux) looks like this, but we could consider changing it to make it more "GitHub Oriented" in the future.

Popular != Good 
(In regards to the repo / code structure, <3 it as a system ofc)

> As for the Documentation folder, I think we might add that and setup a subfolder for each folder of the source, much like the WeeBins folder is organized, and add one markdown file for each source code file.. we might even let the Makefile add these folders and Markdown files if they don't exist.. definitely on a todo list, might be of great help for new contributors :)

Explaining why / how code works is definitely 
refreshing to see, it just has to be readable..

**Comment by ElectronicsArchiver** [comment]
Btw, you might wanna enable `Discussions` if you 
care to talk about code / .. with people~

**Pull request closed without merging**
