### PR TITLE
Some Visual Changes

### PR DESCRIPTION
**Pull request by DragonIvanRussia**
I remade ASCII art, added a color for notes and used it.
In theory it should work.

I hope everything is correct.

### CODE REVIEW

**Comment by Mastcharub** [comment]
Hello! Did you test your code before pulling?

**Comment by mell-o-tron** [comment]
I think there's something wrong with the new ASCII art (or with extended ASCII, in general)
image

I like how it looks in the file though :)

**Comment by DragonIvanRussia** [comment]
Yep, I think it may be the problem with the Extendent ASCII, because different encodings exist.
Decided to make it simpler now.
image

**Comment by mell-o-tron** [comment]
Uhm, I must say I kind of prefer the other one (or the current one, at that). If you could try to make the extended characters render correctly (whenever you have some time), that would be a valuable contribution.

**Comment by DragonIvanRussia** [comment]
Digging trought information online I found out that QEMU uses CP437 for ASCII (a.k.a. most used character set in PCs according to Wikipedia).
So saving in Sublime Text in DOS encoding can fix it.

**Comment by DragonIvanRussia** [comment]
It does work. You need to save documents and text with CP437 encoding.
Снимок экрана от 2022-09-11 11-29-41

**Comment by DragonIvanRussia** [comment]
I decided to close the pull request since the CMD mode was removed and I feel like remade ascii art won't be used until some time.

**Comment by mell-o-tron** [comment]
Some ascii art will eventually be added to the new shell as well, but I don't think that'll be before the first experimental release of the kernel. You can still make a pr with the new .txt file only, without any changes to the software.

**Pull request closed without merging**
