### PR TITLE
added support for creating iso file

### PR DESCRIPTION
**Pull request by pdlashwin**

### CODE REVIEW

**Comment by mell-o-tron** [comment]
Thanks! I'll test it and eventually merge it before the next update :)

**Comment by Ashwin-Paudel** [comment]
ok

**Comment by AnantTiwari-Naman** [comment]
ok

**Comment by jumps-are-op** [comment]
ok

**Comment by mell-o-tron** [comment]
It's been a while lol, sorry, we've been focusing on other parts of the project, would you mind solving the conflicts and integrating this with our new makefile?

**Comment by mell-o-tron** [comment]
I'm closing this, hope you'll have the time to make another after solving the conflicts :(

**Pull request closed without merging**
